### ISSUE TITLE
Fibers build error on io.js

### ISSUE THREAD

**Issue by reggi** [yortus/asyncawait#15]
```
thomas@workstation:new$ npm i asyncawait --save
npm info it worked if it ends with ok
npm info using npm@2.7.1
npm info using node@v1.6.2
npm WARN package.json new@1.0.0 No description
npm WARN package.json new@1.0.0 No repository field.
npm WARN package.json new@1.0.0 No README data
npm info attempt registry request try #1 at 14:26:19
npm http request GET http://registry.npmjs.org/asyncawait
npm http 304 http://registry.npmjs.org/asyncawait
npm info install asyncawait@0.7.4 into /Users/thomas/Desktop/recents/wallpaper/new
npm info installOne asyncawait@0.7.4
npm info preinstall asyncawait@0.7.4
npm info attempt registry request try #1 at 14:26:20
npm http request GET http://registry.npmjs.org/bluebird
npm info attempt registry request try #1 at 14:26:20
npm http request GET http://registry.npmjs.org/fibers
npm info attempt registry request try #1 at 14:26:20
npm http request GET http://registry.npmjs.org/lodash
npm http 304 http://registry.npmjs.org/fibers
npm http 200 http://registry.npmjs.org/bluebird
npm http 200 http://registry.npmjs.org/lodash
npm info retry fetch attempt 1 at 14:26:21
npm info attempt registry request try #1 at 14:26:21
npm http fetch GET http://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http fetch 200 http://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm info install fibers@1.0.5 into /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait
npm info install bluebird@2.3.11 into /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait
npm info install lodash@2.4.1 into /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait
npm info installOne fibers@1.0.5
npm info installOne bluebird@2.3.11
npm info installOne lodash@2.4.1
npm info preinstall fibers@1.0.5
npm info build /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/fibers
npm info linkStuff fibers@1.0.5
npm info install fibers@1.0.5

> fibers@1.0.5 install /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@1.6.2 | darwin | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/Users/thomas/.nvm/versions/io.js/v1.6.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thomas/.nvm/versions/io.js/v1.6.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thomas/.node-gyp/1.6.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/thomas/.node-gyp/1.6.2',
gyp info spawn args   '-Dmodule_root_dir=/Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/fibers',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in namespace 'v8'; did you mean simply 'SetResourceConstraints'?
                v8::SetResourceConstraints(isolate, constraints);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                SetResourceConstraints
../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
        void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
             ^
1 error generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/thomas/.nvm/versions/io.js/v1.6.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/thomas/.nvm/versions/io.js/v1.6.2/bin/iojs" "/Users/thomas/.nvm/versions/io.js/v1.6.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/fibers
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
Build failed
npm info preinstall lodash@2.4.1
npm info build /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/lodash
npm info linkStuff lodash@2.4.1
npm info install lodash@2.4.1
npm info postinstall lodash@2.4.1
npm info preinstall bluebird@2.3.11
npm info build /Users/thomas/Desktop/recents/wallpaper/new/node_modules/asyncawait/node_modules/bluebird
npm info linkStuff bluebird@2.3.11
npm info install bluebird@2.3.11
npm info postinstall bluebird@2.3.11
npm info fibers@1.0.5 Failed to exec install script
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/thomas/.nvm/versions/io.js/v1.6.2/bin/iojs" "/Users/thomas/.nvm/versions/io.js/v1.6.2/bin/npm" "i" "asyncawait" "--save"
npm ERR! node v1.6.2
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm info preuninstall fibers@1.0.5
npm info uninstall fibers@1.0.5
npm info postuninstall fibers@1.0.5
npm info preuninstall asyncawait@0.7.4
npm info uninstall asyncawait@0.7.4
npm info postuninstall asyncawait@0.7.4

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomas/Desktop/recents/wallpaper/new/npm-debug.log
```

**Comment by reggi** [comment]
https://github.com/laverdet/node-fibers/issues/203

**Comment by yortus** [comment]
Hi @reggi,

This is an issue with `node-fibers`. Unfortunately there's nothing that can be done about it in this repo.

Just as a heads-up, I'm working on a variant of this lib that can use ES6 generators instead of fibers, and it will works nicely with `iojs` so far. Not sure when I'll have it ready though. Work in progress is at [yortus/asyncx](https://github.com/yortus/asyncx).

**Comment by yortus** [comment]
Closing as non-actionable.
