### ISSUE TITLE
exception is not thrown as expected when doing concurrent awaits

### ISSUE THREAD

**Issue by rshmelev** [yortus/asyncawait#32]
code: 

```
var fs = require('fs');
var Promise = require('bluebird');
var async = require('asyncawait/async');
var await = require('asyncawait/await');


// A function that returns a promise.
function delay(milliseconds) {
    return Promise.delay(milliseconds);
}

var parallelThreadFunc = function() {
    console.log("1");
    await(delay(1010));
    console.log("2");
    throw new Error("sfdfsfds");
};

var parallelThreadAsync = async(parallelThreadFunc);

// Another synchronous-looking function written in async/await style.
var program = async.thunk (function () {
    try  {
        console.log('zero...');
        // this line was edited after submitting the issue, 
        // it was starting with "async", however bug is reproduced with await of course
        await(parallelThreadAsync(), parallelThreadAsync());
    } catch (ex) {
        console.log('Caught an error', ex);
    }
    return 'Finished!';
});

// Execute program() and print the result.

program()(function (err, result) {
    console.log(result);
});

```

node --version
v4.2.4

mac os yosemite

tested on both npm asyncawait and manually downloaded from github

........ so here what we see is that try..catch block does not work at all for exceptions thrown from parallelThreadAsync.

```
zero...
1
1
2
2
Caught an error [Error: sfdfsfds]
Finished!
Unhandled rejection Error: sfdfsfds
    at parallelThreadFunc (/somedir/asyncawait-probable-bug.js:16:11)
    at tryBlock (/somedir/node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/somedir/node_modules/asyncawait/src/async/fiberManager.js:26:9)

Unhandled rejection Error: sfdfsfds
    at parallelThreadFunc (/somedir/asyncawait-probable-bug.js:16:11)
    at tryBlock (/somedir/node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/somedir/node_modules/asyncawait/src/async/fiberManager.js:26:9)
```

**Comment by yortus** [comment]
Hi @rshmelev,

Thanks, I've investigated this and found a bug in `asyncawait` in its handling of concurrent cases. I'm just about to push/publish v1.0.3 which fixes this.

 There is a little typo in your sample code, the line:
```javascript
        async(parallelThreadAsync(), parallelThreadAsync());
```
should be:
```javascript
        await(parallelThreadAsync(), parallelThreadAsync());
```

Can you please give v1.0.3 a try to verify the fix?

**Comment by rshmelev** [comment]
Heh, that's true, it was 4 AM when I was submitting the issue :) 
Now i've fixed the description code and log.

**Comment by rshmelev** [comment]
Was not able to reproduce on my machine with v1.0.3... so the bug seems to be fixed.  
when are you going to push it to NPM?

**Comment by yortus** [comment]
It's already published.

Thanks for testing, closing this now...
